/* Set this after deploying Code.gs as a Google Apps Script Web App. */
const API_URL = 'https://script.google.com/macros/s/AKfycbyCM7Mcm-y1QPnIhnDvrfDeVaR7BTlAW7QdOOX6nkicz53v_z2oT_tLxGGeSpAlEn4l/exec';
const state = { kind: 'agent', masters: { agents: [], grades: [], schools: [] }, selectedAgent: null, autocompleteIndex: -1, user: null, token: localStorage.getItem('fu_token') || '', rows: [] };
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const fmtDate = (d) => new Intl.DateTimeFormat('id-ID', { dateStyle: 'full' }).format(d);
function toast(message, error = false) { const el = $('#toast'); el.textContent = message; el.className = `toast show${error ? ' error' : ''}`; setTimeout(() => el.className = 'toast', 3000); }
async function api(route, options = {}) { if (API_URL.includes('URL_APPS')) throw new Error('Konfigurasi API_URL belum diisi.'); const url = new URL(API_URL); url.searchParams.set('route', route); if (options.params) Object.entries(options.params).forEach(([k, v]) => v !== '' && v != null && url.searchParams.set(k, v)); const res = await fetch(url, { method: options.method || 'GET', headers: options.method === 'POST' ? { 'Content-Type': 'text/plain;charset=utf-8' } : undefined, body: options.method === 'POST' ? JSON.stringify({ route, ...options.body }) : undefined }); const json = await res.json(); if (!json.ok) throw new Error(json.error || 'Request gagal.'); return json.data || json; }
async function loadMasters() { try { state.masters = await api('masters'); $('#agentName').placeholder = 'Ketik nama Agen...'; } catch (e) { $('#agentName').placeholder = 'Master data belum tersedia'; $('#loginError').textContent = e.message; } }
function escapeHtml(v) { return String(v ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function setLoginMode(kind) { state.kind = kind; $$('.tab').forEach(t => t.classList.toggle('active', t.dataset.kind === kind)); $('#agentFields').classList.toggle('hidden', kind !== 'agent'); $('#adminFields').classList.toggle('hidden', kind !== 'admin'); $('#agentName').required = kind === 'agent'; $('#agentPin').required = kind === 'agent'; $('#adminPassword').required = kind === 'admin'; if (kind === 'admin') { resetSelectedAgent(); closeAgentSuggestions(); } }
function resetSelectedAgent() { state.selectedAgent = null; state.autocompleteIndex = -1; $('#selectedAgentBranch').textContent = ''; $('#pinField').classList.add('hidden'); $('#agentPin').required = false; $('#agentPin').value = ''; }
function renderAgentSuggestions() { const input = $('#agentName'), query = input.value.trim().toLocaleLowerCase(); const list = $('#agentSuggestions'); state.autocompleteIndex = -1; if (!query) { closeAgentSuggestions(); return; } const matches = state.masters.agents.filter(a => String(a.name || '').toLocaleLowerCase().includes(query)).slice(0, 8); list.innerHTML = matches.length ? matches.map((agent, i) => `<button type="button" class="autocomplete-option" role="option" data-index="${i}"><strong>${escapeHtml(agent.name)}</strong><span>${escapeHtml(agent.branch || 'Branch belum tersedia')}</span></button>`).join('') : '<div class="autocomplete-empty">Agen tidak ditemukan.</div>'; input.setAttribute('aria-expanded', 'true'); list.classList.add('open'); list.querySelectorAll('.autocomplete-option').forEach(option => option.onclick = () => selectAgent(matches[Number(option.dataset.index)])); }
function selectAgent(agent) { if (!agent) return; state.selectedAgent = agent; $('#agentName').value = agent.name; $('#selectedAgentBranch').textContent = agent.branch ? `Branch: ${agent.branch}` : ''; $('#pinField').classList.remove('hidden'); $('#agentPin').required = true; $('#agentPin').focus(); closeAgentSuggestions(); $('#loginError').textContent = ''; }
function closeAgentSuggestions() { const list = $('#agentSuggestions'); if (!list) return; list.classList.remove('open'); $('#agentName').setAttribute('aria-expanded', 'false'); }
function moveAgentSelection(direction) { const options = [...document.querySelectorAll('.autocomplete-option')]; if (!options.length) return; state.autocompleteIndex = (state.autocompleteIndex + direction + options.length) % options.length; options.forEach((option, i) => option.classList.toggle('active', i === state.autocompleteIndex)); }
function initAgentAutocomplete() { const input = $('#agentName'); input.addEventListener('input', () => { if (!state.selectedAgent || input.value !== state.selectedAgent.name) resetSelectedAgent(); renderAgentSuggestions(); }); input.addEventListener('focus', () => { if (input.value.trim()) renderAgentSuggestions(); }); input.addEventListener('keydown', e => { if (e.key === 'ArrowDown') { e.preventDefault(); moveAgentSelection(1); } else if (e.key === 'ArrowUp') { e.preventDefault(); moveAgentSelection(-1); } else if (e.key === 'Enter' && state.autocompleteIndex >= 0) { e.preventDefault(); const option = document.querySelectorAll('.autocomplete-option')[state.autocompleteIndex]; if (option) option.click(); } else if (e.key === 'Escape') closeAgentSuggestions(); }); document.addEventListener('click', e => { if (!e.target.closest('.autocomplete-wrap')) closeAgentSuggestions(); }); }
async function login(e) { e.preventDefault(); const btn = $('#loginButton'); btn.disabled = true; btn.classList.add('loading'); $('#loginError').textContent = ''; try { if (state.kind === 'agent' && !state.selectedAgent) throw new Error('Pilih Agen dari hasil pencarian terlebih dahulu.'); const body = state.kind === 'admin' ? { kind: 'admin', password: $('#adminPassword').value } : { kind: 'agent', name: state.selectedAgent.name, pin: $('#agentPin').value }; const data = await api('login', { method: 'POST', body }); state.token = data.token; state.user = data.user; localStorage.setItem('fu_token', state.token); showApp(); await renderDashboard(); } catch (err) { $('#loginError').textContent = err.message; } finally { btn.disabled = false; btn.classList.remove('loading'); } }
function showApp() { $('#loginView').classList.add('hidden'); $('#appView').classList.remove('hidden'); const u = state.user; $('#sidebarName').textContent = u.name; $('#sidebarBranch').textContent = u.branch; $('#userAvatar').textContent = (u.name || 'A').charAt(0).toUpperCase(); $('#todayLabel').textContent = fmtDate(new Date()); }
function nav(view) { $$('.nav-item').forEach(n => n.classList.toggle('active', n.dataset.view === view)); $('#pageTitle').textContent = view === 'dashboard' ? 'Overview' : view === 'plan' ? 'Buat Plan FU' : 'History'; if (view === 'dashboard') renderDashboard(); if (view === 'plan') renderPlanForm(); if (view === 'history') renderHistory(); }
async function renderDashboard() { const content = $('#pageContent'); content.innerHTML = '<div class="panel"><div class="empty">Memuat overview...</div></div>'; try { const route = state.user.kind === 'admin' ? 'admin/rows' : 'rows'; const data = await api(route, { params: { token: state.token, date: new Date().toISOString().slice(0, 10) } }); const total = data.summary.totalPlan; content.innerHTML = `<section class="hero"><div><p class="eyebrow" style="color:#8ce0d6">GOOD TO SEE YOU</p><h3>${escapeHtml(state.user.name)}</h3><p>${escapeHtml(state.user.branch)} · Here is your follow-up plan for today.</p></div>${state.user.kind === 'admin' ? '' : '<button class="primary" data-go="plan">+ Buat Plan FU</button>'}</section><div class="stat-grid"><div class="stat-card"><div class="stat-label">Total Plan FU hari ini</div><div class="stat-value">${total}</div></div><div class="stat-card"><div class="stat-label">Jumlah item</div><div class="stat-value">${data.summary.itemCount}</div></div><div class="stat-card"><div class="stat-label">Target follow-up</div><div class="stat-value">${Object.keys(data.summary.byTarget).length}</div></div></div><div class="panel"><div class="panel-title"><h3>Aktivitas hari ini</h3><button class="secondary" data-go="history">Lihat history</button></div>${tableHtml(data.rows.slice(0, 5))}</div>`; $$('[data-go]').forEach(b => b.onclick = () => nav(b.dataset.go)); } catch (e) { handleAuth(e); content.innerHTML = `<div class="panel empty">${escapeHtml(e.message)}</div>`; } }
function renderPlanForm() { const opts = (arr) => arr.map(v => `<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join(''); $('#pageContent').innerHTML = `<section class="form-card"><div class="form-head"><div><p class="eyebrow">DAILY WORK PLAN</p><h3>Plan FU</h3></div><label class="plan-date">Tanggal<input id="planDate" type="date" required value="${new Date().toISOString().slice(0, 10)}"></label><button class="secondary" id="addRow">+ Tambah Data</button></div><form id="planForm"><div id="planRows"></div><div class="form-actions"><button class="primary" type="submit" id="savePlans">Simpan Plan FU</button></div></form></section>`; const add = () => { const wrap = $('#planRows'); const n = wrap.children.length + 1; const el = document.createElement('div'); el.className = 'plan-row'; el.innerHTML = `<div class="row-head"><span>DATA ${n}</span><button type="button" class="remove" aria-label="Hapus">×</button></div><div class="row-fields"><label>Plan FU<input name="plan" type="number" min="0" step="1" required placeholder="0"></label><label>Grade<select name="grade" required><option value="">Pilih grade</option>${opts(state.masters.grades)}</select></label><label>Nama Sekolah<select name="school" required><option value="">Pilih sekolah</option>${opts(state.masters.schools)}</select></label><label>Yang di-FU<select name="target" required><option value="">Pilih target</option><option>Orang Tua</option><option>Siswa</option></select></label></div>`; el.querySelector('.remove').onclick = () => { if (wrap.children.length > 1) el.remove(); else toast('Minimal satu item Plan FU.', true); }; wrap.appendChild(el); }; add(); $('#addRow').onclick = add; $('#planForm').onsubmit = async e => { e.preventDefault(); const btn = $('#savePlans'); btn.disabled = true; try { const items = $$('#planRows .plan-row').map(row => ({ planFu: row.querySelector('[name="plan"]').value, grade: row.querySelector('[name="grade"]').value, school: row.querySelector('[name="school"]').value, target: row.querySelector('[name="target"]').value })); await api('rows', { method: 'POST', body: { token: state.token, date: $('#planDate').value, rows: items } }); toast('Plan FU berhasil disimpan.'); nav('dashboard'); } catch (err) { handleAuth(err); toast(err.message, true); } finally { btn.disabled = false; } }; }
async function renderHistory() { const content = $('#pageContent'); content.innerHTML = `<section class="panel"><div class="panel-title"><div><p class="eyebrow">YOUR ACTIVITY</p><h3>History Plan FU</h3></div></div><div class="filters"><label>Tanggal<input id="filterDate" type="date"></label><label>Grade<select id="filterGrade"><option value="">Semua grade</option>${state.masters.grades.map(v => `<option>${escapeHtml(v)}</option>`).join('')}</select></label><label>Nama Sekolah<select id="filterSchool"><option value="">Semua sekolah</option>${state.masters.schools.map(v => `<option>${escapeHtml(v)}</option>`).join('')}</select></label><label>Yang di-FU<select id="filterTarget"><option value="">Semua target</option><option>Orang Tua</option><option>Siswa</option></select></label></div><button class="secondary" id="applyFilters">Terapkan filter</button><div id="historyResult" style="margin-top:18px"><div class="empty">Memuat history...</div></div></section>`; const load = async () => { try { const data = await api(state.user.kind === 'admin' ? 'admin/rows' : 'rows', { params: { token: state.token, date: $('#filterDate').value, grade: $('#filterGrade').value, school: $('#filterSchool').value, target: $('#filterTarget').value, agent: $('#filterAgent')?.value || "", branch: $('#filterBranch')?.value || "" } }); $('#historyResult').innerHTML = `<div class="summary-line"><span>Total Plan: <strong>${data.summary.totalPlan}</strong></span><span>Jumlah item: <strong>${data.summary.itemCount}</strong></span></div>${tableHtml(data.rows)}`; } catch (e) { handleAuth(e); } }; $('#applyFilters').onclick = load; await load(); }
function tableHtml(rows) { if (!rows.length) return '<div class="empty">Belum ada data Plan FU.</div>'; return `<div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Plan FU</th><th>Grade</th><th>Nama Sekolah</th><th>Yang di-FU</th>${state.user?.kind === 'admin' ? '<th>Agen</th>' : ''}</tr></thead><tbody>${rows.map(x => `<tr><td>${escapeHtml(x.date)}</td><td><strong>${x.plan}</strong></td><td>${escapeHtml(x.grade)}</td><td>${escapeHtml(x.school)}</td><td>${escapeHtml(x.target)}</td>${state.user?.kind === 'admin' ? `<td>${escapeHtml(x.agentName)}</td>` : ''}</tr>`).join('')}</tbody></table></div>`; }
function handleAuth(e) { if (/session|login|akses/i.test(e.message)) { localStorage.removeItem('fu_token'); state.token = ''; $('#appView').classList.add('hidden'); $('#loginView').classList.remove('hidden'); } }
$('#loginForm').onsubmit = login; initAgentAutocomplete(); $$('.tab').forEach(t => t.onclick = () => setLoginMode(t.dataset.kind)); $$('.nav-item').forEach(n => n.onclick = () => nav(n.dataset.view)); $('#logoutButton').onclick = async () => { try { await api('logout', { params: { token: state.token } }); } catch {} localStorage.removeItem('fu_token'); location.reload(); };
(async function init() { setLoginMode('agent'); await loadMasters(); if (state.token) { try { const data = await api('session', { params: { token: state.token } }); state.user = data.user; showApp(); await renderDashboard(); } catch { localStorage.removeItem('fu_token'); } } })();
